/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class UdpQueueManager {
  constructor(bufferDurationMs?: number | undefined | null)
  createQueue(ip: string, port: number, bufferDurationMs?: number | undefined | null): number
  pushPacket(queueKey: number, packet: Buffer): boolean
  deleteQueue(queueKey: number): boolean
  localAddress(): string
  close(): void
  clearQueue(queueKey: number): boolean
  stats(): UdpQueueStats
  queueInfo(queueKey: number): QueueInfo
  updateQueueTarget(queueKey: number, ip: string, port: number): boolean
  sendNow(queueKey: number, packet: Buffer): boolean
}

export interface QueueInfo {
  queuedPackets: number
  capacityPackets: number
}

export interface UdpQueueStats {
  packetsSent: number
  packetsDropped: number
}
