/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class UdpQueueManager {
  constructor(bufferDurationMs?: number | undefined | null)
  createQueue(bufferDurationMs?: number | undefined | null): number
  pushPacket(queueKey: number, packet: Buffer): boolean
  drainQueue(queueKey: number, nowNs: number): Buffer | null
  drainAll(nowNs: number): Array<DrainItem>
  resetPacing(queueKey: number): void
  deleteQueue(queueKey: number): boolean
  clearQueue(queueKey: number): boolean
  stats(): UdpQueueStats
  queueInfo(queueKey: number): QueueInfo
}

export interface DrainItem {
  queueKey: number
  data: Buffer
}

export interface QueueInfo {
  queuedPackets: number
  capacityPackets: number
}

export interface UdpQueueStats {
  packetsQueued: number
  packetsDropped: number
}
